### PR TITLE
Add product display

### PR DESCRIPTION
**Pull request by Kimkykie**
Add specification to product
Add product slug
Add product display

Products are being fetched from db. You can now view them on homepage and on product page.
We will need to discuss how we will fetch "trending products, featured products, hot deals, related products"

@willikay11 I have an issue while creating a product. Category defaults to laptop and desktops, Kindly assist here.

You can review this and add suggestions. Also for images do we need to have a standard size for product cover?

### CODE REVIEW

**Comment by kwoshvick** [comment]
@Kimkykie Please add a few test product examples for each category as seed.

**Comment by Kimkykie** [comment]
Hey @willikay11 kindly check the add to cart I have pushed

**Comment by Kimkykie** [comment]
I have added product checkout page and redeem coupon capability. Please review @willikay11 @kwoshvick 
I am still facing issues with create category @willikay11

**Comment by Kimkykie** [comment]
Add wishlist
Product slug now working in categories
When testing for wishlist add 2 or more items then try adding first item in wishlist to cart and tell  me how it behaves

**Comment by willikay11** [comment]
@Kimkykie I have reviewed the add to cart process. So far so good. I have been able to do the following
- [X] Add item to cart
- [X] Remove item from cart
- [X] View the items
----------------------------------------------------------------------------------------------
- Cart
Having items in the dropdown cart, the image is too big to fit. We can create thumbnails when uploading the product images.
The checkout option takes me to a login page, was able to login, took me to the checkout page, input fake credit card information but wasn't able to complete the process.
While checking out we should also allow the customer/user to checkout without having to login in.
----------------------------------------------------------------------------------------------
- Wish list
Added a product, then tried to add another and it failed. Removed what I had initially added and attempted to add again but it didn't work.

**Comment by kwoshvick** [comment]
@willikay11 for the payment it will come after this feature is approve. Then for checkout its highly advisable for one to be logged in for them to checkout. All major stores you need to login to purchase. This also will serve us better in terms of understanding customers based on their purchase.

**Comment by willikay11** [comment]
@kwoshvick let's stay with the login feature but add an option to register. We will also need to work on the login UI, doesn't look exciting.

**Pull request merged**
